# Generated by Django 3.2.3 on 2021-05-27 01:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clinica', '0002_alter_agenda_horario'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='agenda',
            table='agenda',
        ),
        migrations.AlterModelTable(
            name='consulta',
            table='consulta',
        ),
        migrations.AlterModelTable(
            name='especialidade',
            table='especialidade',
        ),
        migrations.AlterModelTable(
            name='medico',
            table='medico',
        ),
    ]
