# Generated by Django 3.2.3 on 2021-05-27 03:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clinica', '0003_auto_20210526_2256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medico',
            name='especialidade',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='clinica.especialidade'),
        ),
    ]
