# Generated by Django 3.2.3 on 2021-05-30 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clinica', '0004_alter_medico_especialidade'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='consulta',
            table='usuario',
        ),
    ]
